alias lal='ls -l --almost-all'
alias ll='ls -l'
alias ls='ls --human-readable -C --classify $__COLOR_OPTIONS'
alias lsl='lal | less'
alias dir='dir --human-readable $__COLOR_OPTIONS'
alias vdir='vdir --human-readable $__COLOR_OPTIONS'
