alias ll='ls -l'
alias lla='ls -l --almost-all'
alias ls='ls --human-readable -C --classify $__COLOR_OPTIONS'
alias lss='lla | less'
alias dir='dir --human-readable $__COLOR_OPTIONS'
alias vdir='vdir --human-readable $__COLOR_OPTIONS'
