alias cd..='cd ..'
alias cls='clear'
alias df='pydf'
alias du='ncdu'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias fhere='find . -name '
alias free='free -mht'
alias grep='grep --color=auto'
alias h.='history'
alias hf='history | grep'
alias ll='ls -lhA'
alias ls='ls -CF --color=auto'
alias lsl='ls -lhFA | less'
alias mkdir='mkdir -pv'
alias myip='curl http://ipecho.net/plain; echo'
alias pf='ps -e | grep'
alias ps='ps aux'
alias psg='ps aux | grep -v grep | grep -i -e VSZ -e'
alias top='htop'
alias stow='stow -v'
alias wget='wget -c'
